using System.Collections.ObjectModel;

namespace ID3_Tag_Editor.Models
{
    public class ComboboxCollections
    {
        public static ObservableCollection<string> AllGenres = new ObservableCollection<string>()
            {
                "","Blues","Classic Rock","Country","Dance","Disco","Funk","Grunge","Hip-Hop",
                "Jazz","Metal","New Age","Oldies","Other","Pop","R&B","Rap","Reggae","Rock",
                "Techno","Industrial","Alternative","Ska","Death Metal","Pranks","Soundtrack",
                "Euro-Techno","Ambient","Trip-Hop","Vocal","Jazz+Funk","Fusion","Trance","Classical",
                "Instrumental","Acid","House","Game","Sound Clip","Gospel","Noise","AlternRock",
                "Bass","Soul","Punk","Space","Meditative","Instrumental Pop","Instrumental Rock",
                "Ethnic","Gothic","Darkwave","Techno-Industrial","Electronic","Pop-Folk","Eurodance",
                "Dream","Southern Rock","Comedy","Cult","Gangsta","Top 40","Christian Rap","Pop/Funk",
                "Jungle","Native American","Cabaret","New Wave","Psychadelic","Rave","Showtunes",
                "Trailer","Lo-Fi","Tribal","Acid Punk","Acid Jazz","Polka","Retro","Musical",
                "Rock & Roll","Hard Rock","Cinematic"
            };

        public static ObservableCollection<string> AllLanguages = new ObservableCollection<string>()
            {
                "","Abkhazian","Achinese","Acoli",
                "Adangme","Adygei","Afar","Afrihili","Afrikaans",
                "Afro-Asiatic (Other)","Ainu","Akan","Akkadian","Albanian",
                "Aleut","Algonquian languages","Altaic (Other)","Amharic",
                "Angika","Apache languages","Arabic","Aragonese","Aramaic",
                "Arapaho","Arawak","Armenian","Artificial (Other)",
                "Assamese","Asturian; Bable","Athapascan languages","Australian languages",
                "Austronesian (Other)","Avaric","Avestan","Awadhi",
                "Aymara","Azerbaijani","Balinese","Baltic (Other)",
                "Baluchi","Bambara","Bamileke languages","Banda languages",
                "Bantu (Other)","Basa","Bashkir","Basque","Batak languages",
                "Beja","Belarusian","Bemba","Bengali","Berber (Other)",
                "Bhojpuri","Bihari","Bikol","Bini; Edo","Bislama",
                "Blin; Bilin","Bosnian","Braj","Breton","Buginese",
                "Bulgarian","Buriat","Burmese","Caddo","Caucasian (Other)",
                "Cebuano","Celtic (Other)","Central American Indian (Other)","Central Khmer",
                "Chagatai","Chamic languages","Chamorro","Chechen",
                "Cherokee","Cheyenne","Chibcha","Chinese","Chinook jargon",
                "Chipewyan","Choctaw","Chuukese","Chuvash","Classical Nepal Bhasa",
                "Cook Islands Maori","Coptic","Cornish","Corsican","Cree",
                "Creek","Creoles and pidgins (Other)","Crimean Turkish","Croatian",
                "Cushitic (Other)","Czech","Dakota","Danish","Dargwa",
                "Delaware","Dinka","Dogri","Dogrib","Dravidian (Other)",
                "Duala","Dutch, Middle (ca.1050-1350)","Dyula","Dzongkha","Eastern Frisian",
                "Efik","Egyptian (Ancient)","Ekajuk","Elamite","English",
                "English based (Other)","English, Middle (1100-1500)","English, Old (ca.450-1100)",
                "Erzya","Esperanto","Estonian","Ewe","Ewondo",
                "Fang","Fanti","Faroese","Fijian","Finnish","Finno-Ugrian (Other)",
                "Flemish","Fon","French-based (Other)","French","French, Middle (ca.1400-1600)",
                "French, Old (842-ca.1400)","Friulian","Fulah","Ga","Galibi Carib",
                "Galician","Ganda","Gayo","Gbaya","Geez","Georgian",
                "German","German, Middle High (ca.1050-1500)","German, Old High (ca.750-1050)",
                "Germanic (Other)","Gilbertese","Gondi","Gorontalo","Gothic",
                "Grebo","Greek, Ancient (to 1453)","Greek, Modern (1453-)","Greenlandic",
                "Guarani","Gujarati","Gwich´in","Haida","Haitian Creole","Hausa",
                "Hawaiian","Hebrew","Herero","Hiligaynon","Himachali",
                "Hindi","Hiri Motu","Hittite","Hmong","Hungarian",
                "Hupa","Iban","Icelandic","Ido","Igbo","Ijo languages",
                "Iloko","Inari Sami","Indic (Other)","Indo-European (Other)",
                "Indonesian","Ingush","Interlingua (International Auxiliary Language Association)",
                "Interlingue","Inuktitut","Inupiaq","Iranian (Other)",
                "Irish","Irish, Middle (900-1200)","Irish, Old (to 900)","Iroquoian languages",
                "Italian","Japanese","Javanese","Jingpho","Judeo-Arabic",
                "Judeo-Persian","Kabardian","Kabyle","Kamba","Kannada",
                "Kanuri","Kara-Kalpak","Karachay-Balkar","Karelian","Karen languages",
                "Kashmiri","Kashubian","Kawi","Kazakh","Khasi",
                "Khoisan (Other)","Khotanese","Kikuyu; Gikuyu","Kimbundu","Kinyarwanda",
                "Klingon","Komi","Kongo","Konkani","Korean","Kosraean",
                "Kpelle","Kru languages","Kumyk","Kurdish","Kurukh","Kutenai",
                "Kwanyama","Kyrgyz","Ladino","Lahnda","Lamba","Land Dayak languages",
                "Lao","Latin","Latvian","Letzeburgesch","Lezghian","Limburgish",
                "Lingala","Lithuanian","Lojban","Low German","Lower Sorbian","Lozi",
                "Luba-Katanga","Luba-Lulua","Luiseno","Lule Sami","Lunda","Luo (Kenya and Tanzania)",
                "Lushai","Macedo-Romanian","Macedonian","Madurese","Magahi","Maithili",
                "Makasar","Malagasy","Malay","Malayalam","Maldivian","Maltese",
                "Manchu","Mandar","Mandingo","Manipuri","Manobo languages","Manx",
                "Maori","Mapuche","Marathi","Mari","Marshallese","Marwari",
                "Masai","Mayan languages","Mende","Mi'kmaq; Micmac","Minangkabau",
                "Mirandese","Miscellaneous languages","Mohawk","Moksha","Moldavian",
                "Mon-Khmer (Other)","Mongo","Mongolian","Mossi","Multiple languages",
                "Munda languages","N'Ko","Nahuatl languages","Nauru","Navajo; Navaho",
                "Ndonga","Neapolitan","Nepal Bhasa","Nepali","Nias",
                "Niger-Kordofanian (Other)","Nilo-Saharan (Other)","Niuean","Nogai",
                "Norse, Old","North American Indian","North Ndebele","Northern Frisian",
                "Northern Sami","Northern Sotho","Norwegian","Norwegian Bokmal","Nubian languages",
                "Nyamwezi","Nyanja","Nyankole","Nynorsk Norwegian","Nyoro",
                "Nzima","Occitan (post 1500)","Oirat","Ojibwa","Old Church Slavonic",
                "Oriya","Oromo","Osage","Ossetic","Otomian languages","Pahlavi",
                "Palauan","Pali","Pampanga","Pangasinan","Papiamento",
                "Papuan (Other)","Persian","Persian, Old (ca.600-400 B.C.)","Philippine (Other)",
                "Phoenician","Pilipino","Pohnpeian","Polish","Portuguese-based (Other)",
                "Portuguese","Prakrit languages","Provencal, Old (to 1500)","Punjabi","Pushto",
                "Quechua","Rajasthani","Rapanui","Romance (Other)","Romanian",
                "Romansh","Romany","Rundi","Russian","Salishan languages","Samaritan Aramaic",
                "Sami languages (Other)","Samoan","Sandawe","Sango","Sanskrit",
                "Santali","Sardinian","Sasak","Scots","Scottish Gaelic",
                "Selkup","Semitic (Other)","Serbian","Serer","Shan",
                "Shona","Sichuan Yi","Sicilian","Sidamo","Sign Languages",
                "Siksika","Sindhi","Sinhala; Sinhalese","Sino-Tibetan (Other)","Siouan languages",
                "Skolt Sami","Slave (Athapascan)","Slavic (Other)","Slovak","Slovenian",
                "Sogdian","Somali","Songhai languages","Soninke","Sorbian languages",
                "South American Indian (Other)","South Ndebele","Southern",
                "Southern Altai","Southern Sami","Spanish","Sranan Tongo","Sukuma",
                "Sumerian","Sundanese","Susu","Swahili","Swati",
                "Swedish","Swiss German","Syriac","Tagalog","Tahitian",
                "Tai (Other)","Tajik","Tamashek","Tamil","Tatar",
                "Telugu","Tereno","Tetum","Thai","Tibetan","Tigre",
                "Tigrinya","Timne","Tiv","Tlingit","Tok Pisin","Tokelau",
                "Tonga (Nyasa)","Tonga (Tonga Islands)","Tsimshian","Tsonga",
                "Tswana","Tumbuka","Tupi languages","Turkish","Turkish, Ottoman (1500-1928)",
                "Turkmen","Tuvalu","Tuvinian","Twi","Udmurt","Ugaritic",
                "Ukrainian","Umbundu","Undetermined","Upper Sorbian","Urdu",
                "Uyghur","Uzbek","Vai","Valencian","Venda","Vietnamese",
                "Volapuk","Votic","Wakashan languages","Walamo","Walloon",
                "Waray","Washo","Welsh","Western Frisian","Wolof",
                "Xhosa","Yakut","Yao","Yapese","Yiddish","Yoruba",
                "Yupik languages","Zande languages","Zapotec","Zazaki","Zenaga",
                "Zhuang; Chuang","Zulu","Zuni"
            };

        public static ObservableCollection<string> AllMoods = new ObservableCollection<string>()
            {
                "","Angry","Groovy","Happy","Party","Quirky","Rockin",
                "Sad","Soothing","Spooky","Sunday Brunch","Trippy",
                "Work","Romantic"
            };

        public static ObservableCollection<string> AllVersions = new ObservableCollection<string>()
            {
                "3","4"
            };

        public static ObservableCollection<string> AllKeys = new ObservableCollection<string>()
            {
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key",
                "",
                "A",
                "A (minor)",
                "A flat",
                "A flat (minor)",
                "A sharp",
                "A sharp (minor)",
                "B",
                "B (minor)",
                "B flat",
                "B flat (minor)",
                "B sharp",
                "B sharp (minor)",
                "C",
                "C (minor)",
                "C flat",
                "C flat (minor)",
                "C sharp",
                "C sharp (minor)",
                "D",
                "D (minor)",
                "D flat",
                "D flat (minor)",
                "D sharp",
                "D sharp (minor)",
                "E",
                "E (minor)",
                "E flat",
                "E flat (minor)",
                "E sharp",
                "E sharp (minor)",
                "F",
                "F (minor)",
                "F flat",
                "F flat (minor)",
                "F sharp",
                "F sharp (minor)",
                "G",
                "G (minor)",
                "G flat",
                "G flat (minor)",
                "G sharp",
                "G sharp (minor)",
                "off key"
        };
    }
}
